// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLX6j8BDpmPCX8iIfBTkn3Kx4PVKOXSyA',
    appId: '1:615630753332:android:773a234c094be07c0e0461',
    messagingSenderId: '615630753332',
    projectId: 'petroapp-2438',
    storageBucket: 'petroapp-2438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByk-kZMOOjJKMleGGJpuAVassht7ruNIA',
    appId: '1:615630753332:ios:13975bc568539bef0e0461',
    messagingSenderId: '615630753332',
    projectId: 'petroapp-2438',
    storageBucket: 'petroapp-2438.appspot.com',
    androidClientId: '615630753332-3d1cr3k4rshv7r353vajgk7dhi0oc8r1.apps.googleusercontent.com',
    iosClientId: '615630753332-5de69fgktk45l2u8bs8c7gd022tgmcer.apps.googleusercontent.com',
    iosBundleId: 'fspo.itmo.y2438.petroapp',
  );
}