// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVOsQMr4l_ebHVIZ6fzuNaBpCfaCg_Rg',
    appId: '1:517523749339:android:13eed2a9f1ad1a7433cffe',
    messagingSenderId: '517523749339',
    projectId: 'newsapp-a4f6c',
    storageBucket: 'newsapp-a4f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhSbFA8pOhaiUK9IuDveZmFxiit7yol3Y',
    appId: '1:517523749339:ios:1f3b00c00d9d882b33cffe',
    messagingSenderId: '517523749339',
    projectId: 'newsapp-a4f6c',
    storageBucket: 'newsapp-a4f6c.appspot.com',
    androidClientId: '517523749339-7qobm5t91k8lm9cj3aord5ag9k14pl6s.apps.googleusercontent.com',
    iosClientId: '517523749339-5563vvqp9lhetifdh653vmu7v4v2sfp8.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
